#pragma once

/* Cursor speed */
#define ANALOG_JOYSTICK_SPEED_MAX 5
#define ANALOG_JOYSTICK_SPEED_REGULATOR 10

#define ANALOG_JOYSTICK_Y_AXIS_PIN F5
#define ANALOG_JOYSTICK_X_AXIS_PIN F4

#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y